# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      SWIFT: swift
    steps:
    - uses: actions/checkout@v3
    - name: Check Swift
      run: which swift
    - name: Build
      run: make build
    - name: Run tests
      run: make test
